default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 3306 %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: realworld_production
  username: realworld
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

